name: API Gateway CI/CD

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'api-gateway/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'api-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Service Config
        run: docker run -p 8888:8888 -d service-config:latest

      - name: Run Service Register
        run: docker run -p 8761:8761 -d service-register:latest

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: api-gateway
        run: mvn -B package --file pom.xml

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to registry
        working-directory: ./api-gateway
        run: |
          docker build -t roomsproject/api-gateway:latest .
          docker push roomsproject/api-gateway:latest
