name: AuthService CI/CD

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'AuthService/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'AuthService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore AuthService/AuthService.sln

      - name: Build solution
        run: dotnet build AuthService/AuthService.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test AuthService/AuthService.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=TestResults.trx"

      - name: Publish test results
        if: failure() || always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults.trx'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: AuthService/AuthService
        run: |
          docker build -t roomsproject/auth-service:latest .
          docker push roomsproject/auth-service:latest
