name: DM Service CI/CD

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'WebSocketsDMService/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'WebSocketsDMService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./dm-service
        run: mvn -B package --file pom.xml

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to registry
        working-directory: ./dm-service
        run: |
          docker build -t roomsproject/dm-service:latest .
          docker push roomsproject/dm-service:latest
