name: Room Service CI/CD
on:
  push:
    branches: [ "develop" ]
    paths:
      - 'RoomService/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'RoomService/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
      - name: Restore dependencies
        run: dotnet restore RoomService/RoomService.sln

      - name: Build solution
        run: dotnet build RoomService/RoomService.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test RoomService/RoomService.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=TestResults.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: '**/TestResults.trx'
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        working-directory: RoomService/RoomService
        run: |
          docker build -t roomsproject/room-service:latest .
          docker push roomsproject/room-service:latest
