name: Service Register CI/CD

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'service-register/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'service-register/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Service Config
        run: docker run -p 8888:8888 -d roomsproject/service-config:latest

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./service-register
        run: mvn -B package --file pom.xml

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to registry
        working-directory: ./service-register
        run: |
          docker build -t roomsproject/service-register:latest .
          docker push roomsproject/service-register:latest
